services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    env_file:
      - .env
    ports:
      - "9000:9000" # expose PHP-FPM on host
